export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie } from '#app/composables/cookie';
export { prerenderRoutes, useRequestHeaders, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from '#vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, defineModel, defineOptions, defineSlots, mergeModels, toValue, useModel, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, Component, ComponentPublicInstance, ComputedRef, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode } from 'vue';
export { injectHead, useHead, useSeoMeta, useHeadSafe, useServerHead, useServerSeoMeta, useServerHeadSafe } from '@unhead/vue';
export { useInit } from '../src/composables/init';
export { default as mangaData } from '../src/composables/manga-data';
export { defineShortcuts } from '../node_modules/.pnpm/@nuxt+ui@2.10.0_vue@3.3.8_webpack@5.89.0/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts';
export { useCopyToClipboard } from '../node_modules/.pnpm/@nuxt+ui@2.10.0_vue@3.3.8_webpack@5.89.0/node_modules/@nuxt/ui/dist/runtime/composables/useCopyToClipboard';
export { useFormGroup } from '../node_modules/.pnpm/@nuxt+ui@2.10.0_vue@3.3.8_webpack@5.89.0/node_modules/@nuxt/ui/dist/runtime/composables/useFormGroup';
export { createPopper, usePopper } from '../node_modules/.pnpm/@nuxt+ui@2.10.0_vue@3.3.8_webpack@5.89.0/node_modules/@nuxt/ui/dist/runtime/composables/usePopper';
export { _useShortcuts, useShortcuts } from '../node_modules/.pnpm/@nuxt+ui@2.10.0_vue@3.3.8_webpack@5.89.0/node_modules/@nuxt/ui/dist/runtime/composables/useShortcuts';
export { useTimer } from '../node_modules/.pnpm/@nuxt+ui@2.10.0_vue@3.3.8_webpack@5.89.0/node_modules/@nuxt/ui/dist/runtime/composables/useTimer';
export { useToast } from '../node_modules/.pnpm/@nuxt+ui@2.10.0_vue@3.3.8_webpack@5.89.0/node_modules/@nuxt/ui/dist/runtime/composables/useToast';
export { useUI } from '../node_modules/.pnpm/@nuxt+ui@2.10.0_vue@3.3.8_webpack@5.89.0/node_modules/@nuxt/ui/dist/runtime/composables/useUI';
export { useColorMode } from '../node_modules/.pnpm/@nuxtjs+color-mode@3.3.0/node_modules/@nuxtjs/color-mode/dist/runtime/composables';
export { useLocalForage } from '../node_modules/.pnpm/nuxt3-localforage@0.1.1_localforage@1.10.0/node_modules/nuxt3-localforage/dist/runtime/composables';
export { useNuxtDevTools } from '../node_modules/.pnpm/@nuxt+devtools@1.0.0_nuxt@3.8.1_vite@4.5.0/node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools';
export { definePageMeta } from '../node_modules/.pnpm/nuxt@3.8.1_eslint@8.53.0_typescript@5.2.2_vite@4.5.0/node_modules/nuxt/dist/pages/runtime/composables';